### PR TITLE
Everything works.

### PR DESCRIPTION
**Pull request by gduscher**
Improved documentation

### CODE REVIEW

**Review by ssomnath — CHANGES_REQUESTED** [review]
@gduscher - 
1. I had already made the same changes to ``dataset.py`` in your other branch ``dev-gerd``. We will have merge conflicts again. 
2. Do you want to move your changes from ``plot_visualizers.py`` to a notebook? Don't we have a notebook that does similar things? Please delete redundant examples

**Comment by gduscher** [comment]
Some changes I made earlier somehow did not make it into the master branch. Some were crucial for functions.
How can we merge?
Also, I thought I saw a test for dataset.py, which disappeared from my branch.
Looks like I did took a wrong turn somewhere.
Anyway, I'll consolidate the examples to notebooks and start working on the dataset.py tests.

**Comment by ssomnath** [comment]
@gduscher - you have two branches - ``dev_gerd`` and the one you appear to be working on now ``dev_gerd2``. I added the unit testing framework for ``dev_gerd`` and not ``dev_gerd2``

**Comment by gduscher** [comment]
OK, got it.

**Comment by gduscher** [comment]
Please disregard all the changes from dev-gerd2. 
I was operating under the assumption that the pull from dev-gerd was accepted and master is on par with that branch and dev-gerd2.
That was obviously not the case.

**Comment by ssomnath** [comment]
@gduscher - what do we do about this PR? do you want me to close (reject)?

**Comment by gduscher** [comment]
Please delete this pull request,
I merged everything over to the dev-gerd branch before it was merged with master.
I'll delete the branch

Gerd

**Comment by ssomnath** [comment]
Deleting since contents were merged in #73

**Pull request closed without merging**
