### PR TITLE
Improved examples

### PR DESCRIPTION
**Pull request by gduscher**

### CODE REVIEW

**Comment by ssomnath** [comment]
@ziatdinovmax recently moved some of the examples to notebooks. However, the python counterparts to the new notebooks continue to exist and you seem to have modified the python scripts @gduscher . We will need to migrate your changes to the notebook and then delete the python scripts to avoid confusion going forward. This is the reason I haven't merged your PR just yet.

**Comment by ssomnath** [comment]
@gduscher - Please see #38 . ``sidpy.Dimension.dimension_type`` could use an Enum instead of strings. This applies to the code in ``sidpy/viz/dataset_viz.py``

Also, as I mentioned, we need to copy your updates in your example python scripts into their notebook equivalents [here](https://github.com/pycroscopy/sidpy/tree/master/notebooks/00_basic_usage) and then remove your python scripts

**Comment by ssomnath** [comment]
I am attempting to clean up this branch to the extent possible. @gduscher - I would like for you to do the following in order to accept this pull request:
1. ensure that the two notebooks under the [00_basic_usage](https://github.com/pycroscopy/sidpy/tree/dev-gerd/notebooks/00_basic_usage) work
2. Related to the first point. Delete the files under ``examples/viz_dataset/`` given that the crux of the topics have been covered in [plot_dataset](https://github.com/pycroscopy/sidpy/blob/dev-gerd/notebooks/00_basic_usage/plot_dataset.ipynb)

**Comment by gduscher** [comment]
Only the create_dataset notebook in 00_basic_usage works at this point with the new version .
I'll try to work on the other one tonight and will delete the files under viz.

**Comment by gduscher** [comment]
Done,
However, I don't see my push yet.

**Review by ssomnath — APPROVED** [review]
The example: ``plot_visualizers`` is still broken. We probably don't need it and can delete it. Approving this PR for now

**Pull request merged**
